name: Android CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: set up enviroments
        env: 
          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
        run: echo $GOOGLE_SERVICES > ./app/google-services.json
        
      - name: Build with Gradle
        run: ./gradlew clean build
